name: Test Node.js App

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci
      ## Tests.
      - name: Run tests
        run: npm run test
      - name: Test ciclotomico
        run: npm run lint
      - name: Test coverage
        run: npm run test:coverage
